### PR TITLE
Minor UI changes and some error checking

### PR DESCRIPTION
**Pull request by a8f**
Note that although the KeypressLibrary directory was changed in the solution to match with the git repo, the DllImport has not been changed.

### CODE REVIEW

**Comment by Paymh** [comment]
I also think we should keep the brace style (new line for braces) consistent throughout the whole project just for ease of reading. But other the what I commented on above looks great to me. Good work

**Comment by Paymh** [comment]
> It doesn't for me

The nature of that check should always return true, regardless of if it is a blank string or not
4f97ffe45be622242312409b62a76fa2

So it's weird that it doesn't just re-run setup every time, regardless the second check should cover all based.

> Note that although the KeypressLibrary directory was changed in the solution to match with the git repo, the DllImport has not been changed.   

I amended the last commit, it should build the dll directly into the debug/release folder of the main project now

**Comment by a8f** [comment]
I'm not checking if a string contains empty string, I'm checking if an array of strings contains a string equal to empty string. If you run the setup and enter an empty line for one of the parameters it was causing trouble so I added this.

**Comment by Paymh** [comment]
> I'm not checking if a string contains empty string, I'm checking if an array of strings contains a string equal to empty string

Yeah scratch that, I misread, sorry

**Pull request merged**
